// src/App.tsx
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount, useReadContract } from "wagmi";
import {
  CLUB_TREASURY_USDC_ADDRESS,
  CLUB_TREASURY_USDC_ABI,
} from "./abi/ClubTreasuryUSDC";

function App() {
  const { address, isConnected } = useAccount();

  const {
    data: rawBalance,
    isPending: balanceLoading,
    error: balanceError,
  } = useReadContract({
    address: CLUB_TREASURY_USDC_ADDRESS,
    abi: CLUB_TREASURY_USDC_ABI,
    functionName: "treasuryBalanceUSDC", // 🔥 must exactly match Solidity
  });

  const balanceBigInt = rawBalance as bigint | undefined;
  const balanceDisplay = balanceBigInt
    ? Number(balanceBigInt) / 1_000_000 // assuming 6 decimals (USDC-style)
    : 0;

  return (
    <div
      style={{
        minHeight: "100vh",
        padding: "2rem",
        background: "#020617",
        color: "white",
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
      }}
    >
      <header
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "2rem",
        }}
      >
        <div>
          <h1 style={{ margin: 0, fontSize: "1.8rem" }}>Club Treasury</h1>
          <p style={{ marginTop: "0.35rem", color: "#9ca3af", fontSize: "0.9rem" }}>
            USDC on Base • Voting & Attendance
          </p>
        </div>
        <ConnectButton />
      </header>

      {!isConnected && (
        <p style={{ color: "#9ca3af" }}>
          Connect your wallet to view the treasury and participate in club decisions.
        </p>
      )}

      {isConnected && (
        <main style={{ display: "grid", gap: "1.5rem", maxWidth: 820 }}>
          {/* Treasury Card */}
          <section
            style={{
              padding: "1.5rem",
              borderRadius: "0.75rem",
              background: "rgba(15,23,42,0.95)",
              border: "1px solid rgba(148,163,184,0.3)",
            }}
          >
            <h2 style={{ marginTop: 0, marginBottom: "0.75rem" }}>
              Treasury Balance
            </h2>

            {balanceLoading && <p>Loading balance…</p>}

            {balanceError && (
              <div style={{ color: "#f97373", fontSize: "0.9rem" }}>
                <p style={{ marginBottom: "0.25rem" }}>
                  Error reading balance. Check ABI, address, and network.
                </p>
                <code style={{ fontSize: "0.75rem", whiteSpace: "pre-wrap" }}>
                  {String(balanceError.message ?? balanceError)}
                </code>
              </div>
            )}

            {!balanceLoading && !balanceError && (
              <p style={{ fontSize: "1.4rem", fontWeight: 600 }}>
                {balanceDisplay.toLocaleString(undefined, {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2,
                })}{" "}
                USDC
              </p>
            )}

            <p style={{ marginTop: "0.6rem", color: "#9ca3af", fontSize: "0.85rem" }}>
              Contract:{" "}
              <span style={{ fontFamily: "monospace" }}>
                {CLUB_TREASURY_USDC_ADDRESS.slice(0, 6)}…
                {CLUB_TREASURY_USDC_ADDRESS.slice(-4)}
              </span>
            </p>
          </section>

          {/* Placeholder sections for next features */}
          <section
            style={{
              padding: "1.25rem",
              borderRadius: "0.75rem",
              background: "rgba(15,23,42,0.9)",
              border: "1px dashed rgba(148,163,184,0.4)",
            }}
          >
            <h3 style={{ marginTop: 0, marginBottom: "0.5rem" }}>Proposals (coming next)</h3>
            <p style={{ color: "#9ca3af", fontSize: "0.9rem" }}>
              Here you&apos;ll be able to create proposals to allocate funds,
              vote with your club-weighted voting power, and see results.
            </p>
          </section>

          <section
            style={{
              padding: "1.25rem",
              borderRadius: "0.75rem",
              background: "rgba(15,23,42,0.9)",
              border: "1px dashed rgba(148,163,184,0.4)",
            }}
          >
            <h3 style={{ marginTop: 0, marginBottom: "0.5rem" }}>Attendance (coming next)</h3>
            <p style={{ color: "#9ca3af", fontSize: "0.9rem" }}>
              This section will let members enter the on-chain attendance code
              generated by admins to check into events and earn participation credit.
            </p>
          </section>
        </main>
      )}

      {isConnected && (
        <footer style={{ marginTop: "2rem", fontSize: "0.8rem", color: "#6b7280" }}>
          Connected as{" "}
          <span style={{ fontFamily: "monospace" }}>
            {address?.slice(0, 6)}…{address?.slice(-4)}
          </span>
        </footer>
      )}
    </div>
  );
}

export default App;